#!/usr/bin/env python3
"""Regenerates Sounds.lua from whatever is sitting in the Sounds folder.

WoW cannot list a directory at runtime, so the list has to exist in code.
Run this after adding or removing files.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ADDON = os.path.join(os.path.dirname(HERE), "GoofyAhhForever")
SOUNDS = os.path.join(ADDON, "Sounds")
OUT = os.path.join(ADDON, "Sounds.lua")
PLAYABLE = (".ogg", ".mp3")


def pretty(filename):
    name = os.path.splitext(filename)[0]
    name = re.sub(r"[_-]+", " ", name).strip()
    return name[:1].upper() + name[1:]


def main():
    if not os.path.isdir(SOUNDS):
        print("no Sounds folder at", SOUNDS)
        return 1

    files = sorted(f for f in os.listdir(SOUNDS) if f.lower().endswith(PLAYABLE))
    skipped = [f for f in os.listdir(SOUNDS) if not f.lower().endswith(PLAYABLE) and not f.startswith(".")]

    lines = [
        "--------------------------------------------------------------------------------",
        "-- Goofy Ahh Forever - Sounds.lua",
        "--",
        "-- Generated by tools/scan_sounds.py. The game cannot list a folder, so every",
        "-- sound has to be named here. Drop files in Sounds/ and run the script again.",
        "--------------------------------------------------------------------------------",
        "local ADDON, ns = ...",
        "",
        "ns.SOUNDS = {",
    ]
    for f in files:
        lines.append('    { name = "%s", file = "%s" },' % (pretty(f).replace('"', ""), f))
    lines.append("}")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print("%d sounds written to Sounds.lua" % len(files))
    for f in files:
        print("   ", pretty(f), "->", f)
    if skipped:
        print("ignored (not ogg or mp3):", ", ".join(skipped))
    return 0


sys.exit(main())
