--------------------------------------------------------------------------------
-- Goofy Ahh Forever - Sounds.lua
--
-- Generated by tools/scan_sounds.py. The game cannot list a folder, so every
-- sound has to be named here. Drop files in Sounds/ and run the script again.
--------------------------------------------------------------------------------
local ADDON, ns = ...

ns.SOUNDS = {
    { name = "Augh", file = "augh.mp3" },
    { name = "Bonk", file = "bonk.mp3" },
    { name = "Bruh", file = "bruh.mp3" },
    { name = "Emotionaldamage", file = "emotionaldamage.mp3" },
    { name = "Fart", file = "fart.mp3" },
    { name = "Goofylaugh", file = "goofylaugh.mp3" },
    { name = "Huhcat", file = "huhcat.mp3" },
    { name = "Metalpipe", file = "metalpipe.mp3" },
    { name = "Sneezeboom", file = "sneezeboom.mp3" },
    { name = "Vineboom", file = "vineboom.mp3" },
    { name = "Violin", file = "violin.mp3" },
    { name = "Windowserror", file = "windowserror.mp3" },
}
